# Generated by Django 2.2.7 on 2019-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('minimum_temperature', models.PositiveIntegerField(verbose_name='Min Temperature')),
                ('maximum_temperature', models.PositiveIntegerField(verbose_name='Max Temperature')),
                ('wind', models.CharField(max_length=50)),
                ('rain', models.CharField(max_length=20, verbose_name='Rainfall')),
            ],
        ),
    ]
